### ISSUE TITLE
LLNL/mfem

### ISSUE THREAD

**Issue by vsoch** [LLNL/radiuss#21]
- [x] quick example of usage in README
- [ ] issue / PR templates
- [x] coverage / format
- [ ] developer environments

Nice job!

https://github.com/vsoch/contributor-ci-llnl/blob/main/_cfa/cfa-mfem-mfem.md

**Comment by tzanio** [comment]
I just saw this, thank you.

Here are some comments on the outstanding TODO items. Please let me know what you think.

### Todo

- [x] ~Clearly states similar projects, competitors, prior art, etc.~ → This could be contentious, so IMHO it is better handled through external websites like [Wikipedia](https://en.wikipedia.org/wiki/List_of_finite_element_software_packages)
- [ ] The project has issue templates to help the user submitting a new issue. → Good point, we should add this
- [ ] The project provides a pull request template to guide the developer through steps. → Good point, we should add this
- [ ] A container is provided for quick usage/interaction. → That will be awesome 😄 
- [ ] The code is robustly commented. → We have [doxygen](https://docs.mfem.org/html/classmfem_1_1GridFunction.html), but docs can always be improved
- [ ] The documentation states how to run the tests. → We should improve the discussion in [CONTRIBUTING.md](https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#automated-testing)
- [ ] The repository reports code coverage which is >= 90 % → We have a [codecov check](https://github.com/mfem/mfem/pull/2975), but it is definitely not above 90% 😞 
- [ ] The project has a social media handle or account. → We don't have that, though we probably should.

### Done

> The software can quickly output a version.

MFEM is a library, and its version is available to apps that include it. You can also see it with `make info`.

> Different versions of documentation for various releases are available.

This is now available at https://docs.mfem.org/, see https://mfem.org/download/.

> A support contact or email is provided.

This is listed here: https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#contact-information

> The documentation states how to lint and check formatting.

This is mentioned here: https://github.com/mfem/mfem/blob/master/CONTRIBUTING.md#developer-guidelines

> Tests checks for formatting.

We do that: https://github.com/mfem/mfem/runs/6178104680?check_suite_focus=true#step:4:6

> The README.md has one or more examples of usage.

We have a link to https://mfem.org/examples. It is tricky to provide a simple example for MFEM usage, because even the simplest code https://github.com/mfem/mfem/blob/master/examples/ex0.cpp requires some domain knowledge.

**Comment by vsoch** [comment]
Thank you @tzanio ! I've been quietly doing this (in preparation for some future effort), and I've updated the mfem page to your specifications, and it's rendered here: https://vsoch.github.io/contributor-ci-llnl/cfa/cfa-mfem-mfem/#/cfa/.

mfem has a very good score overall - out of all the repos only spack is a bit higher (e.g., 81% to 89%).

Since it's a development library, what would you have in mind for a container? if it builds with spack, I could probably throw together a quick container base and instructions that would allow for development. Is there a dummy example we could include alongside it for an interested party?

**Comment by tzanio** [comment]
> Thank you @tzanio ! I've been quietly doing this (in preparation for some future effort), and I've updated the mfem page to your specifications, and it's rendered here: https://vsoch.github.io/contributor-ci-llnl/cfa/cfa-mfem-mfem/#/cfa/.
> 
> mfem has a very good score overall - out of all the repos only spack is a bit higher (e.g., 81% to 89%).

Thanks @vsoch. I'll report here if/when we make further improvements.

**Comment by tzanio** [comment]
> Since it's a development library, what would you have in mind for a container? if it builds with spack, I could probably throw together a quick container base and instructions that would allow for development. Is there a dummy example we could include alongside it for an interested party?

The simplest thing will be to have a build (with [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mfem/package.py)) including all [examples](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mfem/package.py#L160-L161) and [miniapps](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/mfem/package.py#L162-L163) (we have [many](https://mfem.org/examples/) of these). A more ambitious option is to also enable the support for some of our optional TPLs, e.g. `cuda`, `rocm`, `petsc`, `sundials`, `superlu-dist`, etc.
